// Automatically generated by astro-icon
// fc6e1debf5a08c8778023fefed7db5b1288864a1b4af0c381b724ba05e555db2

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "ic:round-arrow-left"
		| "ic:round-arrow-right"
		| "octicon:triangle-up-24";
}